### ISSUE TITLE
bad tweets help!!!

### ISSUE THREAD

**Issue by melmsie** [Aetheryx/tweetcord#1]
NOTE: Please do not make an issue for security vulnerabilities! Please contact me privately instead (Aetheryx#6969 on Discord).

### The Problem

Please write what the problem you're having is.

MY tweets are BAD

### Steps to Reproduce

Please write down the steps to reproduce this problem.

1. tweet
2. read tweet
3. bad tweet

### Additional Comments

Please write down any additional comments here.

pls tell how to make better tweets :/

**Comment by Aetheryx** [comment]
:angry:

**Comment by yurboisporks** [comment]
I'm having this issue too, pls fix.

**Comment by ParadoxOrigins** [comment]
same pls fix
