### ISSUE TITLE
remove nudes

### ISSUE THREAD

**Issue by Devoxin** [Aetheryx/tweetcord#10]
NOTE: Please do not make an issue for security vulnerabilities! Please contact me privately instead (Aetheryx#2222 on Discord).

### The Problem

Please write what the problem you're having is.

### Steps to Reproduce

Please write down the steps to reproduce this problem.

1. remove nude.js
2. bad lang
3. remove the gem

### Additional Comments
pls remove
Please write down any additional comments here.

**Comment by Devoxin** [comment]
remove the gem

**Comment by Aetheryx** [comment]
k

**Comment by Devoxin** [comment]
how the download ericks.jayess

**Comment by Aetheryx** [comment]
https://discord.js.org/#/docs/main/master/general/welcome

**Comment by ParadoxOrigins** [comment]
WILL YA DUCKING STOP U TWATS

**Comment by Aetheryx** [comment]
hi qt

**Comment by Devoxin** [comment]
no ericks not dicksword

**Comment by Aetheryx** [comment]
@Devoxin https://discord.js.org/#/docs/main/master/general/welcome

**Comment by Devoxin** [comment]
use piethan

**Comment by Aetheryx** [comment]
@Devoxin https://github.com/DV8FromTheWorld/JDA

**Comment by Devoxin** [comment]
@paradoxorigins stfu ur not in on this meme ur so uncool it hurts

**Comment by ParadoxOrigins** [comment]
are you both yoo retarded to use discord

**Comment by Aetheryx** [comment]
@ParadoxOrigins shh bby is ok c'mere

**Comment by ParadoxOrigins** [comment]
too*

**Comment by Devoxin** [comment]
@Aetheryx no dat ge dee ayy lmao i won eriks

**Comment by Aetheryx** [comment]
how do I delete issues

**Comment by Aetheryx** [comment]
@Devoxin big gay

**Comment by ParadoxOrigins** [comment]
baguette tbh
