### ISSUE TITLE
tokens don't work

### ISSUE THREAD

**Issue by Devoxin** [Aetheryx/tweetcord#6]
NOTE: Please do not make an issue for security vulnerabilities! Please contact me privately instead (Aetheryx#2222 on Discord).

### The Problem

Please write what the problem you're having is.

the tokens don wok

### Steps to Reproduce

Please write down the steps to reproduce this problem.

1. try to use tokens from config u pushed
2.  login failed/unauthorized
3.  ???

### Additional Comments

y don they werk
muh boah won't logen

Please write down any additional comments here.

**Comment by Aetheryx** [comment]
pls
