### ISSUE TITLE
Message in Discord when mentioned

### ISSUE THREAD

**Issue by BrutalCSkakan** [Aetheryx/tweetcord#9]
NOTE: Please do not make an issue for security vulnerabilities! Please contact me privately instead (Aetheryx#2222 on Discord).

### The Problem

I cant find any way to send a message to the Discord channel whenever someone mentions me in a tweet. It can probably be done with the "follower stream" but that will also include all of the other non-interesting tweets, is there a way to only get a message in Discord whenever some mentions me, and whenever I write a new tweet/retweet?

I'd just like the "user tweet" but with mentions. 

### Steps to Reproduce

Please write down the steps to reproduce this problem.

1. X
2. X
3. X

### Additional Comments

Please write down any additional comments here.

**Comment by Aetheryx** [comment]
Currently not available. In terms of specific events (e.g. retweets, likes, normal tweets, mentions) it's either everything or nothing. When I pick this project back up, you will be able to filter out events specifically.
